#
#
#
#
#
#
#
site_name: Super Fun Digressions # site_name and site_url are the only required fields
site_url: https://example.com # https://example.com is a placeholder value
nav:
    - workflow: workflow.md
    - setup: setup.md
    - influx: quickstart.md
    - infaqs: infaqs.md
    - gitnotes: gitnotes.md 
    - notes:
        - shellnotes:
            - shell commands:
                - 
            - bash: notemds/bashnotes.md
            
        - vsnotes: notemds/vsnotes.md
#
# theme: 
    # name: material
#
markdown_extensions:
    - admonition
    - pymdownx.highlight
        use_pygments: true
    # - codehilite:
        # use_pygments: true
        # code_header: true
    - toc:
        permalink: True
        toc_depth: 6
    # - markdown_fenced_code_tabs:
        # template: 'default'
#
plugins:
    - search
    - img2fig
#
extra:
  favicon: /img/favicon.ico