site_name: Super Fun Digressions # site_name and site_url are the only required fields
site_url: https://example.com # https://example.com is a placeholder value
nav: 
    - Home: index.md
    - About: about.md
    - vscode: vsnotes.md
    - Github Setup: shellnotes.md 
    - Workflow: workflow.md

plugins:
  - img2fig:
      caption_prefix: "Figure"
      caption_title: "Figures"
      svg_output: false