#
#
#
#
#
#
#
site_name: Super Fun Digressions # site_name and site_url are the only required fields
site_url: https://example.com # https://example.com is a placeholder value
nav:
    - about: about.md 
    - index: index.md
    - influx: quickstart.md
    - gitnotes: gitnotes.md 
    - workflow: workflow.md
    - vsnotes: vsnotes.md
#
markdown_extensions:
  - toc:
      permalink: True
      toc_depth: 6
#
plugins:
    - search
    - img2fig
#
extra:
  favicon: /img/favicon.ico